### ISSUE TITLE
Add 404 responses to the valid responses where you look up by task id or step id

### ISSUE THREAD

**Issue by ntindle** [e2b-dev/agent-protocol#28]
**Is your feature request related to a problem? Please describe.**
The spec is incomplete on the defined behavior of what occurs when you request a task ID that doesn't exist. This is problematic as when not defined its indistinguishable from a 500 error which should have different behavior client side. 

**Describe the solution you'd like**
I'd like 404 messages to be added as a documented response code for this case.

**Describe alternatives you've considered**
We can also not document it, but going forward you could expect people to use 500 in this case which shouldn't be used as there should be no errors that occur when this happens

**Additional context**

**Comment by jakubno** [comment]
Hi @ntindle, thanks for your input. It makes sense! I'll address this one soon. I'll tag you in the PR

**Comment by jakubno** [comment]
Added in https://github.com/e2b-dev/agent-protocol/pull/31

**Comment by jakubno** [comment]
Added in https://github.com/e2b-dev/agent-protocol/pull/31
